config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <h1>Your Task For Today</h1>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="card">
  <%= form_for(@task) do |task| %>
      <%= task.label :title, wrapper_html: { class: 'text-field' }%>
      <%= task.text_field :title%>
      <%= task.label :details %>
      <%= task.text_field :details %>
      <p></p>
      <%= task.check_box :completed %>
      <%= task.label :completed %>
      <%= task.submit %>
  <% end %>
</div>

<div class="footer">
  <p><%= link_to "Back To All Tasks", tasks_path  %></p>
  <p><%= link_to "Back To This Task", task_path(@task)  %></p>
</div>

app/views/tasks/index.html.erb
<div class="task-list">
  <ul>
    <% @tasks.each do |task| %>
    <div class="list-inline">
      <li class="list-inline-item">
      <% if task.completed == true %>
        <%= "✅"%>
      <% else %>
        <%=  "⬜" %>
      <% end %>
  </li>
      <li class="list-inline-item"> <%= link_to task.title, task_path(task) %></li>
      <li class="list-inline-item" id="trash-can"> <%= link_to "🗑", delete_task_path(task), method: :delete %></li>
    </div>
    <% end %>
  </ul>
</div>

<div class="footer">
  <%= link_to "➕ Add Your New Task", tasks_new_path  %>
</div>

app/views/tasks/new.html.erb
<h2>Please Add Your new Task</h2>

<%= form_for(@task) do |task| %>
    <%= task.label :title %>
    <%= task.text_field :title %>
    <%= task.label :details %>
    <%= task.text_field :details %>
    <%= task.submit %>
<% end %>

<p> <%= link_to "Back to Tasks", tasks_path  %>

app/views/tasks/show.html.erb
<div class="card">

  <h3 class="card-header"><%= @task.title %></h3>

  <p class="card-details"> <%= @task.details %></p>

    <% if @task.completed == true %>
      <%= "✅ This task is completed"%>
    <% else %>
      <%=  "⬜ This task has not been completed" %>
    <% end %>
</div>


  <div class="footer">
    <p class="card-status"><%= link_to "Update This Task", edit_task_path %></p>
    <p><%= link_to "Go Back To Your Tasks", tasks_path  %></p>
  </div>